version: '3'
services:
  nginx:
    image: nginx:1.13.5-alpine
    container_name: cake_nginx
    platform: linux/x86_64 # M1チップ対応のため追記
    ports:
      - '8080:80'
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/htdocs:/var/www/html
    networks:
      vpcbr:
        ipv4_address: 172.26.0.2
  php:
    container_name: cake_php
    build: build/cake_php
    platform: linux/x86_64 # M1チップ対応のため追記
    volumes:
      - ./data/htdocs:/var/www/html
    networks:
      vpcbr:
        ipv4_address: 172.26.0.3
  mariadb:
    image: mariadb:10.2
    container_name: cake_db
    platform: linux/x86_64 # M1チップ対応のため追記
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cake
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
      - ./data/mysql:/var/lib/mysql
    networks:
      vpcbr:
        ipv4_address: 172.26.0.4
networks:
  vpcbr:
    ipam:
      driver: default
      config:
      - subnet: 172.26.0.0/16